// This file is auto-generated by TanStack Router
// DO NOT EDIT MANUALLY

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'

const IndexRouteWithChildren = IndexRoute

export const routeTree = rootRoute.addChildren([IndexRouteWithChildren])

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
    }
  }
}
